{{- if .Values.ca.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: diamond-ca--ingress
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
{{- range $i, $org := .Values.PeerOrgs }}
  - host: diamond-ca-{{ $org.Name | lower }}.{{ $.Values.ingress.parentDomain }}
    http:
      paths:
      - path: /
        backend: 
          serviceName: diamond-ca--{{ $org.Name | lower }}
          servicePort: 7054
{{- end }}
  tls:
  - hosts:
{{- range $i, $org := .Values.PeerOrgs }}
    - diamond-ca-{{ $org.Name | lower }}.{{ $.Values.ingress.parentDomain }}
{{- end }}
    secretName: diamond-ca--ingress-tls
{{- end }} {{- /* if ingress.enabled */ -}}
