{{- if (index .Values "diamond-kafka").enabled }}
# Kafka service name is release name dependent
# we specify our service to make configtx.yaml release name independent
apiVersion: v1
kind: Service
metadata:
  name: diamond-kafka-service
  labels:
    name: diamond-kafka-service
spec:
  type: ClusterIP
  ports:
  - name: broker
    port: 9092
    protocol: TCP
    targetPort: kafka
  selector:
    app.kubernetes.io/name: diamond-kafka
{{- end }} {{- /* diamond-kafka.enabled */ -}}
