{{- if .Values.orderer.externalService.enabled }}
{{- range $i, $org := .Values.OrdererOrgs }}
{{- range $i, $host := $org.Specs }}

apiVersion: v1
kind: Service
metadata:
  name: diamond-orderer-external--{{ $org.Name | lower }}--{{ $host.Hostname | lower }}
  labels:
    name: diamond-orderer--{{ $org.Name | lower }}--{{ $host.Hostname | lower }}
    component: diamond-orderer
    fqdn: {{ $host.Hostname }}.{{ $org.Domain }}
    addToExternalHostAliases: "true"
  annotations:
    {{- range $key, $value := $.Values.peer.externalService.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: LoadBalancer
  selector:
    app: diamond-orderer--{{ $org.Name | lower }}--{{ $host.Hostname | lower }}
  ports:
  - protocol: TCP
    port: 7050
    name: grpc
  {{- if $.Values.orderer.cluster.enabled }}
  - protocol: TCP
    port: {{ $.Values.orderer.cluster.port }}
    name: grpc-cluster
  {{- end }}  
---
{{- end }} {{- /* org.Specs */ -}}
{{- end }} {{- /* OrdererOrgs */ -}}
{{- end }} {{- /* If externalService.enabled */ -}}
