apiVersion: v1
kind: Service
metadata:
  name: diamond-orderer-lb
  labels:
    name: diamond-orderer-lb
spec:
  type: ClusterIP
  selector:
    name: diamond-orderer
  ports:
  - protocol: TCP
    port: 7050
    name: grpc
---
