{{- if .Values.peer.externalService.enabled }}
{{- range $i, $org := .Values.PeerOrgs }}
{{- range $peerIndex := until ($org.Template.Count | int) }}
{{- $peer := (printf "peer%s" ($peerIndex | toString)) }}

apiVersion: v1
kind: Service
metadata:
  name: diamond-peer-external--{{ $org.Name | lower }}--{{ $peer | lower }}
  labels:
    name: diamond-peer--{{ $org.Name | lower }}--{{ $peer | lower }}
    component: diamond-peer
    fqdn: {{ $peer }}.{{ $org.Domain }}
    addToExternalHostAliases: "true"
  annotations:
    {{- range $key, $value := $.Values.peer.externalService.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    
spec:
  type: LoadBalancer
  selector:
    name: diamond-peer
    app: diamond-peer--{{ $org.Name | lower }}--{{ $peer | lower }}
  ports:
  - protocol: TCP
    port: 7051
    name: grpc
---
{{- end }} {{- /* Peers */ -}}
{{- end }} {{- /* Orgs */ -}}
{{- end }} {{- /* If externalService.enabled */ -}}
