{{- range $i, $org := .Values.PeerOrgs }}

apiVersion: v1
kind: Service
metadata:
  name: diamond-org-peer--{{ $org.Name | lower }}
  labels:
    name: diamond-org-peer--{{ $org.Name | lower }}
spec:
  type: ClusterIP
  selector:
    name: diamond-peer
    org: diamond-peer--{{ $org.Name | lower }}
  ports:
  - protocol: TCP
    port: 7051
    name: grpc
  - protocol: TCP
    port: 7052
    name: chaincode
---
{{- end }} {{- /* Orgs */ -}}
